Numpy Tutorial

In [ ]:
import numpy as np


In [ ]:
from time import process_time

list vs Array

In [ ]:
python_list=[i for i in range(1000)]
start_time=process_time()
python_list=[i+5 for i in range(1000)]
end_time=process_time()
print(end_time-start_time)

0.00026125300000057194


In [ ]:
np_array=np.array([i for i in range(1000)])
start_time=process_time()
np_array+=5
end_time=process_time()
print(end_time-start_time)

0.0001555990000001728


NUMPY Arrays

In [ ]:
list1=[1,2,3,4]
print(list1)
type(list1)

[1, 2, 3, 4]


list

In [ ]:
np_array=np.array([1,2,3,4])
print(np_array)
type(np_array)

[1 2 3 4]


numpy.ndarray

In [ ]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

In [ ]:
b=np.array([(1,2,3,4),(5,6,7,8)])

In [ ]:
b.shape
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initializing values

In [ ]:
d=np.zeros((4,5))
print(d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
e=np.full((5,4),5)
print(e)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
f=np.eye(4)

In [ ]:
print(f)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
g=np.random.random((3,4))

In [ ]:
print(g)

[[0.38718608 0.14253331 0.87119417 0.83861646]
 [0.60488756 0.57007285 0.81836599 0.76187422]
 [0.84084276 0.3383328  0.13739562 0.14917006]]


In [ ]:
h=np.random.randint(10,100,(3,4))
print(h)

[[50 84 22 28]
 [99 71 85 20]
 [26 72 85 79]]


In [ ]:
i=np.full((3,3),39)

In [ ]:
print(i)

[[39 39 39]
 [39 39 39]
 [39 39 39]]


In [ ]:
listq=[10,20,30,40]
np_array=np.array(listq)
print(np_array)
type(np_array)

[10 20 30 40]


numpy.ndarray

In [ ]:
k=np.random.randint(10,20,(3,3))
print(k)

[[17 17 12]
 [11 13 17]
 [11 16 18]]


In [ ]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)

[[7 8 7]
 [5 1 8]
 [7 7 3]]
[[15 17 13]
 [11 16 16]
 [15 17 11]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[22 25 20]
 [16 17 24]
 [22 24 14]]
[[ -8  -9  -6]
 [ -6 -15  -8]
 [ -8 -10  -8]]
[[105 136  91]
 [ 55  16 128]
 [105 119  33]]
[[0.46666667 0.47058824 0.53846154]
 [0.45454545 0.0625     0.5       ]
 [0.46666667 0.41176471 0.27272727]]
